### ISSUE TITLE
All pictures are saved in landscape orientation

### ISSUE THREAD

**Issue by tradej** [SimpleMobileTools/Simple-Camera#186]
Landscape pictures are saved correctly, portrait pictures are saved rotated 90° clockwise.

App version: 4.1.3 (F-Droid)
Phone: Nokia 5, Android 8.1.0

**Comment by GarciaPL** [comment]
There is an option in the settings which is called Flip front camera photos horizontally, maybe you check if it might fix your issue ? Check it out screenshot here https://github.com/SimpleMobileTools/Simple-Camera/issues/187

**Comment by tradej** [comment]
I tried that and it doesn't work (I am talking about the rear—main—camera), and even if it did, it would be a bug because the problem is not flipping, it is rotating.

**Comment by tibbi** [comment]
should be fixed in 5.1.0, we ill see

**Comment by AlanSanchezP** [comment]
I'm also experiencing this bug

App version: 5.2.0.72 from f-droid
Phone: Redmi 6, Android 9, MIUI 11

**Comment by AlanSanchezP** [comment]
Just noticed that this is the same bug as #234, my photos orientation follow the same pattern

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this

**Comment by ToxicMushroom** [comment]
this still persists in 5.7.0 for me

android 13
lineage os 20
viewer used is com.google.gallery3d

landscape rear camera is correct
portrait rear camera is saved rotated 90 deg
